name: Generate DHL Stadium ICS

on:
  # Schedule: 01:00 UTC on the 1st of every month
  schedule:
    - cron: '0 1 1 * *'

  # Run on push to master branch
  push:
    branches:
      - master

  workflow_dispatch: # manual trigger

jobs:
  generate-ics:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo and allow push with GITHUB_TOKEN
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: master
          persist-credentials: false  # We'll handle token manually

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # 3️⃣ Cache pip dependencies
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 4️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 5️⃣ Generate the ICS file
      - name: Generate ICS
        run: python generate_dhl_ics.py

      # 6️⃣ Commit and push ICS
      - name: Commit and push ICS
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git add dhl_stadium.ics
          git commit -m "Update DHL Stadium ICS" || echo "No changes to commit"
          
          # Use HTTPS with token to push
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/GiladAmar/GreenpointStandiumScraper.git
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}